databases:
  - name: postgresql
    databaseName: postgresql_9gpg
    user: postgresql_9gpg_user

services:
  - type: web
    name: budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false